# Generated by Django 5.2.8 on 2025-11-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicelog',
            old_name='device_id',
            new_name='device',
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='code',
            field=models.CharField(unique=True),
        ),
    ]
